name: Tests

on:
  push:
    branches:
      - '1.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: ['5.5.*', '5.8.*', '6.*']

        include:
          - laravel: '5.5.*'
          - laravel: '5.8.*'
          - laravel: '6.*'

    name: 'PHP ${{ matrix.php }} / ${{ matrix.laravel }}'

    steps:
      - uses: actions/checkout@master

      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '${{ matrix.php }}'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: pcov

      - name: Install Composer dependencies
        run: composer require "illuminate/support:${{ matrix.laravel }}"

      - name: Show laravel version
        run: composer show laravel/framework

      - name: Run tests
        run: php -d pvov.enabled=1 ./vendor/bin/phpunit --coverage-clover=coverage.xml
        continue-on-error: ${{ matrix.php == '7.4' }}

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
